= flowcase, the Flutter Showcase

A *Fl*utter app that sh*owcase*s a dozen or so self-contained Flutter demos.
Most are winnowed down to their minimum for
easier understanding than some of the official
demos which IMHO have a bit of rhetorical flourish that at least takes longer to read.

== Maint

If you change `images/logo.png`, be sure to run

	flutter pub run flutter_launcher_icons

This generates the derivative icon files for all platforms listed in the
icons section of pubspec.yaml.


== stack_rounded

This shows a radiused box, common in this year's layouts, and some
radiused containers.

"Sandy Lion" is a trademark of Rejminet Group only
as applied to the lion image used in this app.
SandyLion (one word) stickers, which our kids loved
when they were young, were formerly made by a company of that name
at https://sandylion.com. That company has either renamed or been absorbed into
Trends International (https://trendsinternational.com/)
and they're not even marketing stickers under that name,
according to a search on their web site.

=== TODO

Add GestureDetectors around the two rounded
containers, with various pop-ups.

Animated background gradient.
